<?php

return [

    // numberDigits determines the number of digits in the code to be generated by auth guard
    "numberDigits"              => env('AUTHGUARD_NUMBER_DIGITS', 6),

    // otpExpirationTime determines the time for the generated code to expire, which must be passed in minutes. example: 1 = 1 minute
    "otpExpirationTime"         => env('AUTHGUARD_EXPIRATION_TIME', 3),

    // maxAttempts determines the number of times a code can be validated in case of an error.
    "maxAttempts"               => env('AUTHGUARD_MAX_ATTEMPTS', 3),

    // validateUserReference determines whether the passed reference should be validated.
    "validateUserReference"     => true,

    // validateUserIpAddress determines whether the user's IP address should be validated.
    "validateUserIpAddress"     => true,

    // validateUserAccessToken determines whether the logged in user's access token should be validated.
    "validateUserAccessToken"   => false,

    // below are the authguard return responses.
    "responses" => [

        // Success Message.
        "success" => [
            'created'    => 'Otp code created successfully',
            'deleted'    => 'Otp code deleted successfully',
            'confirmed'     => "Code confirmed successfully!",
            'resend'        => "Code sent successfully.",
            'founded'    => "otp code found."
        ],

        // Error Messages.
        "error" => [
            'thereIsAlreadyAnActiveCode'    => 'There is already a recently created code that has not yet been confirmed and is within its expiration date.',
            'notFoundCode'                  => 'No verification code for this number; Try again by resending a new code.',
            'expiredCode'                   => "The Code entered has expired the confirmation period; try again by resending a new code.",
            'attemptLimitExceeded'          => "Attempt limit exceeded; try again by resubmitting new code.",
            'invalidCode'                   => "The Code entered is invalid.",
            'confirmCode'                   => "Confirm the code sent to your cell phone and email!",
            'create'                     => "There was a failure creating the otp code.",
            'action'                     => "There was a failure to perform the action.",
        ]

    ]

];